Fix link
Guake/guake-website pull request #12
Opened 2021-08-03 11:35 UTC by tatarianBarbarian

On website now link to contributors graps looks like this:
`<a href="https://github.com/Guake/guake/g
              </p>
            </div>
          </div>raphs/contributors">`

2021-08-03 11:36 UTC, tatarianBarbarian commented
@gsemet take a look plz?

2024-04-05 17:19 UTC, ulidtko requested changes
No. This changes nothing.

The broken link issue was fixed in #9 and #10 — but never deployed.

Due a bus effect mentioned [here](https://github.com/Guake/guake-website/pull/10#issuecomment-660948304).

2024-04-05 18:03 UTC, ulidtko commented
I take that back... you actually have a point.

2024-04-05 18:06 UTC, tatarianBarbarian commented
> I take that back... you actually have a point.

Hm. 3 years passed, and this edit is still actual :smile: 

Is there any way to merge this one?

2024-04-05 18:08 UTC, ulidtko commented
@tatarianBarbarian yes, I'm doing it right now.

Re: 3 years passed — welcome to software :tada: where old mistakes live forever.

2024-04-05 18:15 UTC, ulidtko approved these changes

2024-04-05 18:16 UTC, merged